In [1]:
import pandas as pd

In [4]:
df = pd.read_csv(r'C:\Users\tcaal\Desktop\Learning Python\Data\WeatherHistory.csv')

In [5]:
df.head()

,Formatted Date,Summary,Precip Type,Temperature (C),Apparent Temperature (C),Humidity,Wind Speed (km/h),Wind Bearing (degrees),Visibility (km),Loud Cover,Pressure (millibars),Daily Summary
0,3/26/2006,Mostly Cloudy,rain,5.183333,4.111111,0.91,5.5384,166,9.9820,0,1013.29,Mostly cloudy throughout the day.
1,3/27/2006,Mostly Cloudy,rain,3.722222,2.566667,0.94,5.2003,145,9.9820,0,1013.39,Mostly cloudy throughout the day.
2,3/28/2006,Mostly Cloudy,rain,4.855556,3.705556,0.93,5.6189,170,5.9248,0,1013.45,Mostly cloudy throughout the day.
3,3/29/2006,Foggy,rain,5.211111,5.211111,0.92,4.7656,178,1.2236,0,1013.40,Mostly cloudy throughout the day.
4,3/30/2006,Overcast,rain,6.255556,4.638889,0.92,7.9212,223,7.2128,0,1013.81,Mostly cloudy throughout the day.

In [9]:
df.info() # Describes data set; similar to str() in R

<class 'pandas.DataFrame'>
RangeIndex: 2363 entries, 0 to 2362
Data columns (total 12 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Formatted Date            2363 non-null   datetime64[us]
 1   Summary                   2363 non-null   str
 2   Precip Type               2363 non-null   str
 3   Temperature (C)           2363 non-null   float64
 4   Apparent Temperature (C)  2363 non-null   float64
 5   Humidity                  2363 non-null   float64
 6   Wind Speed (km/h)         2363 non-null   float64
 7   Wind Bearing (degrees)    2363 non-null   int64
 8   Visibility (km)           2363 non-null   float64
 9   Loud Cover                2363 non-null   int64
 10  Pressure (millibars)      2363 non-null   float64
 11  Daily Summary             2363 non-null   str
dtypes: datetime64[us](1), float64(6), int64(2), str(3)
memory usage: 221.7 KB

In [8]:
df['Formatted Date'] = pd.to_datetime(df['Formatted Date']) # Converts type to datetime

In [12]:
# Date things like string

df[df['Formatted Date'].dt.year == 2006]

,Formatted Date,Summary,Precip Type,Temperature (C),Apparent Temperature (C),Humidity,Wind Speed (km/h),Wind Bearing (degrees),Visibility (km),Loud Cover,Pressure (millibars),Daily Summary
0,2006-03-26,Mostly Cloudy,rain,5.183333,4.111111,0.91,5.5384,166,9.9820,0,1013.29,Mostly cloudy throughout the day.
1,2006-03-27,Mostly Cloudy,rain,3.722222,2.566667,0.94,5.2003,145,9.9820,0,1013.39,Mostly cloudy throughout the day.
2,2006-03-28,Mostly Cloudy,rain,4.855556,3.705556,0.93,5.6189,170,5.9248,0,1013.45,Mostly cloudy throughout the day.
3,2006-03-29,Foggy,rain,5.211111,5.211111,0.92,4.7656,178,1.2236,0,1013.40,Mostly cloudy throughout the day.
4,2006-03-30,Overcast,rain,6.255556,4.638889,0.92,7.9212,223,7.2128,0,1013.81,Mostly cloudy throughout the day.
...,...,...,...,...,...,...,...,...,...,...,...,...
213,2006-10-25,Mostly Cloudy,rain,13.033333,13.033333,0.81,14.4578,209,9.9820,0,1012.85,Mostly cloudy throughout the day.
214,2006-10-26,Mostly Cloudy,rain,17.244444,17.244444,0.62,25.0194,221,11.2700,0,1012.15,Mostly cloudy throughout the day.
215,2006-10-27,Mostly Cloudy,rain,17.738889,17.738889,0.53,27.3700,230,11.4471,0,1011.71,Mostly cloudy throughout the day.
216,2006-10-28,Overcast,rain,17.844444,17.844444,0.56,22.2180,251,11.2700,0,1011.28,Mostly cloudy throughout the day.
217,2006-10-29,Mostly Cloudy,rain,18.861111,18.861111,0.56,23.5382,250,11.2700,0,1010.99,Mostly cloudy throughout the day.

In [ ]:
df[df['Formatted Date'].dt.day.name() == 'Monday'] # This didn't work

TypeError: 'str' object is not callable

In [20]:
df = pd.read_csv("C:/Users/tcaal/Desktop/Learning Python/Data/laptopprices.csv",
                encoding = 'ISO-8859-1')

In [21]:
df.sort_values(by = 'Price_usd',
                ascending = True)

,ï»¿laptop_ID,Company,Product,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price_usd
1215,1233,Acer,C740-C9QX (3205U/2GB/32GB/Chrome,Netbook,11.6,1366x768,Intel Celeron Dual Core 3205U 1.5GHz,2GB,32GB SSD,Intel HD Graphics,Chrome OS,1.3kg,191.40
20,21,Asus,Vivobook E200HA,Netbook,11.6,1366x768,Intel Atom x5-Z8350 1.44GHz,2GB,32GB Flash Storage,Intel HD Graphics 400,Windows 10,0.98kg,211.09
1120,1135,Vero,V131 (X5-Z8350/4GB/32GB/FHD/W10),Notebook,13.3,Full HD 1920x1080,Intel Atom X5-Z8350 1.44GHz,4GB,32GB Flash Storage,Intel HD Graphics 400,Windows 10,1.35kg,215.60
31,32,Asus,E402WA-GA010T (E2-6110/2GB/32GB/W10),Notebook,14.0,1366x768,AMD E-Series E2-6110 1.5GHz,2GB,32GB Flash Storage,AMD Radeon R2,Windows 10,1.65kg,218.90
290,295,Acer,Chromebook C910-C2ST,Notebook,15.6,1366x768,Intel Celeron Dual Core 3205U 1.5GHz,2GB,16GB SSD,Intel HD Graphics,Chrome OS,2.19kg,218.90
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1066,1081,Asus,ROG G701VO,Gaming,17.3,IPS Panel Full HD 1920x1080,Intel Core i7 6820HK 2.7GHz,64GB,1TB SSD,Nvidia GeForce GTX 980,Windows 10,3.58kg,4372.50
749,758,HP,Zbook 17,Workstation,17.3,IPS Panel Full HD 1920x1080,Intel Xeon E3-1535M v5 2.9GHz,16GB,256GB SSD,Nvidia Quadro M2000M,Windows 7,3kg,4827.90
610,617,Lenovo,Thinkpad P51,Notebook,15.6,IPS Panel 4K Ultra HD 3840x2160,Intel Xeon E3-1535M v6 3.1GHz,32GB,1TB SSD,Nvidia Quadro M2200M,Windows 10,2.5kg,5388.90
830,839,Razer,Blade Pro,Gaming,17.3,4K Ultra HD / Touchscreen 3840x2160,Intel Core i7 7820HK 2.9GHz,32GB,512GB SSD,Nvidia GeForce GTX 1080,Windows 10,3.49kg,6048.90
196,200,Razer,Blade Pro,Gaming,17.3,4K Ultra HD / Touchscreen 3840x2160,Intel Core i7 7820HK 2.9GHz,32GB,1TB SSD,Nvidia GeForce GTX 1080,Windows 10,3.49kg,6708.90

In [24]:
df[df['Product'] == 'Blade Pro'].sort_values(by = ['Inches','Price_usd'],
                                             ascending = [True,False]) # Sort for product being blade pro and then sort price descending

,ï»¿laptop_ID,Company,Product,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price_usd
1231,1249,Razer,Blade Pro,Gaming,14.0,Full HD 1920x1080,Intel Core i7 7700HQ 2.8GHz,16GB,1TB SSD,Nvidia GeForce GTX 1060,Windows 10,1.95kg,3848.9
778,787,Razer,Blade Pro,Gaming,14.0,Full HD 1920x1080,Intel Core i7 7700HQ 2.8GHz,16GB,512GB SSD,Nvidia GeForce GTX 1060,Windows 10,1.95kg,3188.9
647,655,Razer,Blade Pro,Gaming,14.0,Full HD 1920x1080,Intel Core i7 7700HQ 2.8GHz,16GB,256GB SSD,Nvidia GeForce GTX 1060,Windows 10,1.95kg,2858.9
196,200,Razer,Blade Pro,Gaming,17.3,4K Ultra HD / Touchscreen 3840x2160,Intel Core i7 7820HK 2.9GHz,32GB,1TB SSD,Nvidia GeForce GTX 1080,Windows 10,3.49kg,6708.9
830,839,Razer,Blade Pro,Gaming,17.3,4K Ultra HD / Touchscreen 3840x2160,Intel Core i7 7820HK 2.9GHz,32GB,512GB SSD,Nvidia GeForce GTX 1080,Windows 10,3.49kg,6048.9